#!/usr/bin/env python
"""Unsloth QLoRA fine-tune of Gemma 4 E4B on antibody data.

Day-14 (GPU phase) script. Runs on GCP A100 40GB spot (~5 hrs, ~$5.50).

Training data:
    - 200K OAS heavy chains (formatted as FASTA-like prompts)
    - 50K synthetic instruction pairs:
        prompt:    "Given CDR1=..., CDR2=..., suggest a CDR3 for V_gene=IGHV3-23"
        completion: <observed CDR3>
      generated by AbLang2 masked predictions over the OAS subset.

Eval target: held-out perplexity ≥ 30% lower than base; CDR3 masked-AA top-1
accuracy ≥ 50% (vs. ~25% base).

Output: HF Hub adapter at `${HF_USERNAME}/idiotypeforge-gemma4-e4b-ab-lora`.

Usage:
    python scripts/finetune_gemma4_unsloth.py \\
        --base-model unsloth/gemma-4-e4b \\
        --train-jsonl data/oas/train_200k_instruct.jsonl \\
        --eval-jsonl  data/oas/eval_5k.jsonl \\
        --out runs/gemma4-e4b-ab-lora \\
        --epochs 1 --lr 2e-4 --batch-size 16
"""
from __future__ import annotations

import sys

import click


@click.command()
@click.option("--base-model", default="unsloth/gemma-4-e4b")
@click.option("--train-jsonl", type=click.Path(exists=True))
@click.option("--eval-jsonl", type=click.Path(exists=True))
@click.option("--out", "out_dir", type=click.Path(file_okay=False), default="runs/gemma4-e4b-ab-lora")
@click.option("--epochs", type=int, default=1)
@click.option("--lr", type=float, default=2e-4)
@click.option("--batch-size", type=int, default=16)
@click.option("--seq-len", type=int, default=1024)
@click.option("--push-to-hub/--no-push", default=False)
def main(
    base_model: str,
    train_jsonl: str | None,
    eval_jsonl: str | None,
    out_dir: str,
    epochs: int,
    lr: float,
    batch_size: int,
    seq_len: int,
    push_to_hub: bool,
) -> None:
    """Stub — implement on Day 14 (GPU phase).

    Day-14 implementation:
        1. unsloth.FastLanguageModel.from_pretrained(base_model, load_in_4bit=True)
        2. add_lora(rank=16, alpha=32, target_modules='all-linear')
        3. SFTTrainer with the OAS instruction set
        4. evaluate held-out perplexity + CDR3 masked top-1
        5. save adapter, optionally push to HF Hub
        6. write `runs/.../eval_metrics.json` for the writeup
    """
    click.echo("[stub] Day-14 GPU script. Run on GCP A100 40GB spot.")
    sys.exit(0)


if __name__ == "__main__":
    main()
